export const creatorProducts = [
  {
    id: 'myyfind',
    title: 'MyyFind 趋势雷达',
    subtitle: 'AI 热销捕手',
    kicker: 'myyfind',
    intro: 'AI 趋势雷达实时抓取 TikTok、Instagram、YouTube 等平台的爆品信号。',
    description: '一键查看热度曲线、GMV 预估与选品理由，在对手之前锁定下一款爆品。',
    tags: ['趋势捕捉', '智能选品'],
    image: '/images/preview_detail_1.png',
    imageAlt: 'MyyFind dashboard preview',
    iconBg: '#E8F7F6',
    iconColor: '#20837F',
  },
  {
    id: 'opportunity',
    title: 'Opportunity 协作任务',
    subtitle: '跨境 Campaign',
    kicker: 'opportunity',
    intro: '品牌任务大厅集中推送全球 Campaign brief，报名和跟进都在一个页面完成。',
    description: '自动匹配粉丝画像、报价区间与交付要求，悬浮即可看 payout 与产品包详情。',
    tags: ['品牌 Campaign', '即申即拿'],
    image: '/images/preview_detail_2.png',
    imageAlt: 'Opportunity task board preview',
    iconBg: '#EEF3FF',
    iconColor: '#4059D8',
  },
  {
    id: 'value',
    title: '价值分析 Value Lens',
    subtitle: '内容价值体检',
    kicker: '价值分析',
    intro: 'AI 建模创作者的内容表现与成交链路，量化你的带货含金量。',
    description: '测算 GMV、转化率、复购贡献，生成合作建议书，让谈判底牌一目了然。',
    tags: ['ROI 预估', '智能报告'],
    image: '/images/preview_detail_3.png',
    imageAlt: 'Value analysis dashboard preview',
    iconBg: '#FFF2E9',
    iconColor: '#FF8A38',
  },
  {
    id: 'guidance',
    title: '定位引导 Launchpad',
    subtitle: '定位 & 脚本',
    kicker: '定位引导',
    intro: '以对话式步骤梳理人群洞察与内容主题，帮你快速定下下一支短视频的视角。',
    description: '结合人群画像 + 品类赛道给出脚本结构与推荐货盘，定位完成即可进入创作。',
    tags: ['定位策略', '脚本灵感'],
    image: '/images/preview_detail_4.png',
    imageAlt: 'Launchpad workflow preview',
    iconBg: '#E8F7F6',
    iconColor: '#20837F',
    href: '/products/positioning',
  },
];

export const resourceLinks = {
  learn: [
    { href: '/about', title: 'About MyyShop', desc: 'Platform overview & mission' },
    { href: '/resources/insights', title: 'MyyShop Insights', desc: 'Data-driven market analysis' },
    { href: '/resources/reports', title: 'Industry Reports', desc: 'Trends & benchmarks' },
    { href: '/resources/blog', title: 'Blog', desc: 'Tips, guides & updates' },
  ],
  product: [
    { href: '/comparison', title: 'Product Comparison', desc: 'Compare plans & features' },
    { href: '/products', title: 'Product Features', desc: 'Full capabilities overview' },
    { href: '/resources/user-stories', title: 'User Stories', desc: 'Real creator success stories' },
    { href: '/resources/faq', title: 'FAQ', desc: 'Common questions answered' },
  ],
};
